# Generated by Django 2.1 on 2019-08-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkoutevent',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='customergroup',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='customerunsubscribe',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='dashboard',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='emailrecord',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='emailtask',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='emailtrigger',
            options={'managed': False, 'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='orderevent',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='subscriberactivity',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='topproduct',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='customer_text',
            field=models.TextField(blank=True, null=True, verbose_name='customer_text'),
        ),
    ]
