# Generated by Django 2.1 on 2019-07-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='update_time',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='customergroup',
            name='click_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='邮件单击率'),
        ),
        migrations.AlterField(
            model_name='customergroup',
            name='clicks',
            field=models.IntegerField(blank=True, null=True, verbose_name='点击量'),
        ),
        migrations.AlterField(
            model_name='customergroup',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='customergroup',
            name='open_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='邮件打开率'),
        ),
        migrations.AlterField(
            model_name='customergroup',
            name='opens',
            field=models.IntegerField(blank=True, null=True, verbose_name='打开量'),
        ),
        migrations.AlterField(
            model_name='customergroup',
            name='sents',
            field=models.IntegerField(blank=True, null=True, verbose_name='发送量'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='click_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Click Rate'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='conversion_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Conversion Rate'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='open_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Open Rate'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='repeat_purchase_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Repeat Purchase Rate'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='sent',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sent'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='total_click_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Click Rate'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='total_conversion_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Conversion Rate'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='total_open_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Open Rate'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='total_orders',
            field=models.IntegerField(blank=True, null=True, verbose_name='Orders'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='total_repeat_purchase_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Repeat Purchase Rate'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='total_revenue',
            field=models.FloatField(blank=True, null=True, verbose_name='Revenue'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='total_sent',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sent'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='total_unsubscribe_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Unsubscribe Rate'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='unsubscribe_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Unsubscribe Rate'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='click_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='邮件单击率'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='clicks',
            field=models.IntegerField(blank=True, null=True, verbose_name='点击量'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='open_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='邮件打开率'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='opens',
            field=models.IntegerField(blank=True, null=True, verbose_name='打开量'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='sents',
            field=models.IntegerField(blank=True, null=True, verbose_name='发送量'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='unsubscribe_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='邮件退订率'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='unsubscribes',
            field=models.IntegerField(blank=True, null=True, verbose_name='退订量'),
        ),
        migrations.AlterField(
            model_name='emailtrigger',
            name='click_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='单击比例'),
        ),
        migrations.AlterField(
            model_name='emailtrigger',
            name='email_delay',
            field=models.TextField(blank=True, null=True, verbose_name='发送邮件顺序'),
        ),
        migrations.AlterField(
            model_name='emailtrigger',
            name='members',
            field=models.IntegerField(blank=True, null=True, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='emailtrigger',
            name='open_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='打开邮件比例'),
        ),
        migrations.AlterField(
            model_name='emailtrigger',
            name='trigger_info',
            field=models.TextField(blank=True, null=True, verbose_name='trigger关系'),
        ),
    ]
