# Generated by Django 2.1 on 2019-08-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkoutevent',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='customergroup',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='customerunsubscribe',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='dashboard',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='emailrecord',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='emailtask',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='emailtrigger',
            options={'managed': False, 'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='orderevent',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='subscriberactivity',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='topproduct',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='body_text',
            field=models.TextField(blank=True, null=True, verbose_name='邮件body_text'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='heading_text',
            field=models.TextField(blank=True, null=True, verbose_name='邮件'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='headline',
            field=models.TextField(blank=True, null=True, verbose_name='邮件headline'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='subject',
            field=models.TextField(blank=True, null=True, verbose_name='邮件标题'),
        ),
    ]
