# Generated by Django 2.1 on 2019-07-09 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('open_rate', models.CharField(blank=True, max_length=255, null=True, verbose_name='打开邮件比例')),
                ('click_rate', models.CharField(blank=True, max_length=255, null=True, verbose_name='单机比例')),
                ('members', models.CharField(blank=True, max_length=255, null=True, verbose_name='数量')),
                ('relation_info', models.TextField(blank=True, verbose_name='客户关系')),
                ('customer_list', models.TextField(blank=True, verbose_name='对应客户列表')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'customer_group',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='客户名称')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='客户邮箱')),
                ('register_time', models.DateTimeField(blank=True, null=True, verbose_name='客户注册时间')),
                ('last_cart_time', models.DateTimeField(blank=True, null=True, verbose_name='最近购物时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='EmailGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('open_rate', models.CharField(blank=True, max_length=255, null=True, verbose_name='打开邮件比例')),
                ('click_rate', models.CharField(blank=True, max_length=255, null=True, verbose_name='单机比例')),
                ('members', models.CharField(blank=True, max_length=255, null=True, verbose_name='数量')),
                ('trigger_info', models.TextField(blank=True, verbose_name='trigger关系')),
                ('email_delay', models.TextField(blank=True, verbose_name='发送邮件顺序')),
                ('customer_group_list', models.TextField(blank=True, verbose_name='邮件对应的客户组列表')),
                ('send_rule', models.TextField(blank=True, verbose_name='发送邮件规则')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'email_group',
            },
        ),
        migrations.CreateModel(
            name='EmailInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(blank=True, max_length=255, verbose_name='邮件标题')),
                ('heading_text', models.TextField(blank=True, verbose_name='邮件')),
                ('logo', models.TextField(blank=True, verbose_name='邮件logo')),
                ('banner', models.TextField(blank=True, verbose_name='邮件banner')),
                ('headline', models.TextField(blank=True, verbose_name='邮件headline')),
                ('body_text', models.TextField(blank=True, verbose_name='邮件body_text')),
                ('product_list', models.TextField(blank=True, verbose_name='产品列表')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'email_info',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='店铺名称')),
                ('url', models.CharField(blank=True, max_length=255, unique=True, verbose_name='店铺URL')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='email address')),
                ('token', models.CharField(blank=True, max_length=255, null=True, verbose_name='账号使用标识')),
                ('money_format', models.CharField(blank=True, max_length=255, null=True, verbose_name='店铺money标识')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'store',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='store',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailinfo',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Store'),
        ),
        migrations.AddField(
            model_name='emailgroup',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Store'),
        ),
        migrations.AddField(
            model_name='customers',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Store'),
        ),
        migrations.AddField(
            model_name='customergroup',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Store'),
        ),
    ]
