# Generated by Django 2.1 on 2019-07-18 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190718_1123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailrecord',
            options={'managed': False},
        ),
    ]
