# Generated by Django 2.1 on 2019-08-17 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190816_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailrecord',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'managed': True},
        ),
    ]
