# Generated by Django 2.1 on 2019-07-09 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190709_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=255, verbose_name='产品标识符')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='产品URL')),
                ('uuid', models.CharField(max_length=64, verbose_name='产品唯一标识')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='产品名称')),
                ('image_url', models.CharField(max_length=255, verbose_name='图片URL')),
                ('thumbnail', models.TextField(blank=True, default=None, null=True, verbose_name='缩略图')),
                ('price', models.CharField(max_length=255, verbose_name='产品价格')),
                ('tag', models.CharField(max_length=255, verbose_name='所属标签')),
                ('publish_time', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('url_with_utm', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='产品的带utm构建的url')),
            ],
            options={
                'db_table': 'product',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='产品类目标题')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='产品类目标题url')),
                ('category_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='产品类目id')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Store')),
            ],
            options={
                'db_table': 'product_category',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.ProductCategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Store'),
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('category_id', 'store')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('product_category', 'uuid')},
        ),
    ]
