# Generated by Django 2.1 on 2019-07-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190712_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='邮件ID')),
                ('customer_group_list', models.TextField(blank=True, verbose_name='邮件对应的客户组列表')),
                ('sents', models.IntegerField(blank=True, null=True, verbose_name='发送量')),
                ('opens', models.IntegerField(blank=True, null=True, verbose_name='打开量')),
                ('clicks', models.IntegerField(blank=True, null=True, verbose_name='点击量')),
                ('unsubscribes', models.IntegerField(blank=True, null=True, verbose_name='退订量')),
                ('open_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='邮件打开率')),
                ('click_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='邮件单击率')),
                ('unsubscribe_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='邮件退订率')),
                ('store_id', models.IntegerField(verbose_name='店铺id')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'email_record',
            },
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='customergroup',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='dashboard',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='emailtrigger',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='subscriberactivity',
            options={'managed': False},
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='click_rate',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='clicks',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='open_rate',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='opens',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='sents',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='unsubscribe_rate',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='unsubscribes',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='uuid',
        ),
    ]
