# Generated by Django 2.1 on 2019-08-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_product_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerUnsubscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_uuid', models.CharField(db_index=True, max_length=255, verbose_name='客户的唯一id')),
                ('unsubscribe_status', models.SmallIntegerField(choices=[(0, 'is false'), (1, 'is true'), (2, 'is sleep')], db_index=True, default=0, verbose_name='取消订阅或者休眠')),
                ('unsubscribe_date', models.DateTimeField(blank=True, null=True, verbose_name='取消订阅时间/休眠的截止时间')),
                ('store_id', models.IntegerField(db_index=True, verbose_name='店铺id')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'customer_unsubscribe',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='checkoutevent',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='customergroup',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='dashboard',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='emailrecord',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='emailtask',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'managed': False, 'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='emailtrigger',
            options={'managed': False, 'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='orderevent',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='subscriberactivity',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='topproduct',
            options={'managed': False},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='unsubscribe_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='unsubscribe_status',
        ),
    ]
