# Generated by Django 2.1 on 2019-08-29 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190826_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'managed': False, 'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='emailtrigger',
            options={'ordering': ['-id']},
        ),
    ]
