# Generated by Django 2.1 on 2019-07-18 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190718_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderevent',
            options={},
        ),
    ]
