# Generated by Django 2.1 on 2019-08-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190807_1730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='customerunsubscribe',
            options={},
        ),
        migrations.RemoveField(
            model_name='customerunsubscribe',
            name='customer_uuid',
        ),
        migrations.AddField(
            model_name='customerunsubscribe',
            name='email',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='客户的email'),
        ),
    ]
