# Generated by Django 2.1 on 2019-07-09 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190709_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deshboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.CharField(blank=True, max_length=255, null=True, verbose_name='Revenue')),
                ('orders', models.CharField(blank=True, max_length=255, null=True, verbose_name='Orders')),
                ('repeat_purchase_rate', models.CharField(blank=True, max_length=255, null=True, verbose_name='Repeat Purchase Rate')),
                ('conversion_rate', models.CharField(blank=True, max_length=255, null=True, verbose_name='Conversion Rate')),
                ('sent', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sent')),
                ('open_rate', models.CharField(blank=True, max_length=255, null=True, verbose_name='Open Rate')),
                ('click_rate', models.CharField(blank=True, max_length=255, null=True, verbose_name='Click Rate')),
                ('unsubscribe_rate', models.CharField(blank=True, max_length=255, null=True, verbose_name='Unsubscribe Rate')),
                ('total_revenue', models.CharField(blank=True, max_length=255, null=True, verbose_name='Revenue')),
                ('total_orders', models.CharField(blank=True, max_length=255, null=True, verbose_name='Orders')),
                ('total_repeat_purchase_rate', models.CharField(blank=True, max_length=255, null=True, verbose_name='Repeat Purchase Rate')),
                ('total_conversion_rate', models.CharField(blank=True, max_length=255, null=True, verbose_name='Conversion Rate')),
                ('total_sent', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sent')),
                ('total_open_rate', models.CharField(blank=True, max_length=255, null=True, verbose_name='Open Rate')),
                ('total_click_rate', models.CharField(blank=True, max_length=255, null=True, verbose_name='Click Rate')),
                ('total_unsubscribe_rate', models.CharField(blank=True, max_length=255, null=True, verbose_name='Unsubscribe Rate')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Store')),
            ],
            options={
                'db_table': 'deshboard',
            },
        ),
        migrations.RemoveField(
            model_name='emailgroup',
            name='customer_group_list',
        ),
        migrations.RemoveField(
            model_name='emailgroup',
            name='send_rule',
        ),
        migrations.AddField(
            model_name='emailinfo',
            name='customer_group_list',
            field=models.TextField(blank=True, verbose_name='邮件对应的客户组列表'),
        ),
        migrations.AddField(
            model_name='emailinfo',
            name='html',
            field=models.TextField(blank=True, verbose_name='邮件html'),
        ),
        migrations.AddField(
            model_name='emailinfo',
            name='send_rule',
            field=models.TextField(blank=True, verbose_name='发送邮件规则'),
        ),
        migrations.AddField(
            model_name='emailinfo',
            name='state',
            field=models.SmallIntegerField(choices=[(0, '固定邮件'), (1, '邮件组')], db_index=True, default=1, verbose_name='邮件状态'),
        ),
        migrations.AlterField(
            model_name='customergroup',
            name='click_rate',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='单击比例'),
        ),
        migrations.AlterField(
            model_name='emailgroup',
            name='click_rate',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='单击比例'),
        ),
    ]
