# Generated by Django 2.1 on 2019-08-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190829_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtrigger',
            name='total_sents',
            field=models.IntegerField(blank=True, null=True, verbose_name='flow总发送量'),
        ),
        migrations.AlterField(
            model_name='emailtrigger',
            name='is_open',
            field=models.SmallIntegerField(choices=[(0, 'internal'), (1, 'external')], db_index=True, default=1, verbose_name='是否对外'),
        ),
    ]
