# Generated by Django 2.1 on 2019-08-08 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190807_1807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerunsubscribe',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'managed': True},
        ),
    ]
