# Generated by Django 2.1 on 2019-07-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190709_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='email',
            new_name='customer_email',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='register_time',
        ),
        migrations.AddField(
            model_name='customers',
            name='accept_marketing_status',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'is true'), (1, 'is false')], db_index=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='customers',
            name='clicked_email_times',
            field=models.CharField(blank=True, max_length=255, verbose_name='客户单击邮箱次数'),
        ),
        migrations.AddField(
            model_name='customers',
            name='last_cart_status',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'is empty'), (1, 'is not empty')], db_index=True, null=True, verbose_name='客户最后一次购物车状态'),
        ),
        migrations.AddField(
            model_name='customers',
            name='last_click_email_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='客户最后单击邮箱时间'),
        ),
        migrations.AddField(
            model_name='customers',
            name='last_opened_email_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='客户最后打开邮箱时间'),
        ),
        migrations.AddField(
            model_name='customers',
            name='last_order_status',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'is paid'), (1, 'is unpaid')], db_index=True, null=True, verbose_name='客户最后一次订单状态'),
        ),
        migrations.AddField(
            model_name='customers',
            name='last_order_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='客户最后一次订单时间'),
        ),
        migrations.AddField(
            model_name='customers',
            name='opened_email_times',
            field=models.CharField(blank=True, max_length=255, verbose_name='客户打开邮箱次数'),
        ),
        migrations.AddField(
            model_name='customers',
            name='payment_amount',
            field=models.CharField(blank=True, max_length=255, verbose_name='客户付款金额'),
        ),
        migrations.AddField(
            model_name='customers',
            name='sign_up_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='客户登陆时间'),
        ),
        migrations.AddField(
            model_name='customers',
            name='subscribe_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近购物时间'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='last_cart_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='客户最后一次购物时间'),
        ),
    ]
