# Generated by Django 2.1 on 2019-08-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190829_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtrigger',
            name='total_sents',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='flow总发送量'),
        ),
    ]
