# Generated by Django 2.1 on 2019-08-19 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190817_1405'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'managed': False},
        ),
    ]
