# Generated by Django 2.1 on 2019-08-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190829_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtrigger',
            options={'managed': True, 'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='emailtrigger',
            name='email_trigger_id',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True, verbose_name='email_trigger_id'),
        ),
    ]
