# Generated by Django 2.1 on 2019-07-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190709_1846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AddField(
            model_name='store',
            name='domain',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='店铺domain'),
        ),
    ]
