# Generated by Django 2.1 on 2019-07-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190718_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderevent',
            name='store_id',
            field=models.IntegerField(default=1, verbose_name='店铺id'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='orderevent',
            unique_together={('store_id', 'order_uuid')},
        ),
    ]
