# Generated by Django 2.1 on 2019-08-19 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190819_1003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'managed': True, 'ordering': ['-id']},
        ),
    ]
