# Generated by Django 2.1 on 2019-08-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_store_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='user_id',
            field=models.IntegerField(db_index=True, default=1, verbose_name='用户id'),
            preserve_default=False,
        ),
    ]
