# Generated by Django 2.1 on 2019-08-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190819_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='banner_text',
            field=models.TextField(blank=True, null=True, verbose_name='邮件headline'),
        ),
    ]
