# Generated by Django 2.1 on 2019-08-30 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190830_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtrigger',
            name='is_open',
        ),
    ]
