# Generated by Django 2.1 on 2019-07-10 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190709_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='money_format',
        ),
    ]
