# Generated by Django 2.1 on 2019-07-12 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_emailrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailRecord',
        ),
    ]
