# Generated by Django 2.1 on 2019-07-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190718_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_three', models.TextField(blank=True, null=True, verbose_name='前三天的销售量')),
                ('top_seven', models.TextField(blank=True, null=True, verbose_name='前七天的销售量')),
                ('top_fifteen', models.TextField(blank=True, null=True, verbose_name='前十五天的销售量')),
                ('top_thirty', models.TextField(blank=True, null=True, verbose_name='前三十天的销售量')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'top_product',
            },
        ),
        migrations.AlterModelOptions(
            name='orderevent',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='store',
            name='state',
            field=models.SmallIntegerField(choices=[(0, '新店铺'), (1, '拉过一次数据')], db_index=True, default=0, verbose_name='是否是新店铺'),
        ),
    ]
