# Generated by Django 2.1 on 2019-08-30 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_emailtrigger_is_open'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtrigger',
            options={'managed': False, 'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'managed': True},
        ),
    ]
