# Generated by Django 2.1 on 2019-08-08 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_store_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'managed': False},
        ),
    ]
