# Generated by Django 2.1 on 2019-07-12 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_emailrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customergroup',
            options={},
        ),
    ]
