# Generated by Django 2.1 on 2019-07-19 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190719_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='state',
            new_name='init',
        ),
    ]
