# Generated by Django 2.1 on 2019-08-19 10:21

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_emailtemplate_banner_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='banner_text',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True, verbose_name='邮件headline'),
        ),
    ]
