# Generated by Django 2.1 on 2019-08-08 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190808_1718'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='product',
        #     name='store',
        #     field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Store'),
        #     preserve_default=False,
        # ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='product',
            name='store_id',
        ),
    ]
