# Generated by Django 2.1 on 2019-08-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190819_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='banner_text',
            field=models.TextField(blank=True, null=True, verbose_name='banner_text'),
        ),
    ]
