# Generated by Django 2.1 on 2019-08-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190830_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='op_user',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='opstore用户'),
        ),
    ]
