# Generated by Django 2.1 on 2019-07-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190710_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='hmac',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='hmac'),
        ),
    ]
