# Generated by Django 2.1 on 2019-07-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190719_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='init',
        ),
        migrations.AddField(
            model_name='store',
            name='customer_init',
            field=models.SmallIntegerField(choices=[(0, '新店铺没有拉过customer'), (1, '拉过一次数据')], db_index=True, default=0, verbose_name='店铺是否拉过customer'),
        ),
        migrations.AddField(
            model_name='store',
            name='order_init',
            field=models.SmallIntegerField(choices=[(0, '新店铺没有拉过order'), (1, '拉过一次数据')], db_index=True, default=0, verbose_name='店铺是否拉过order'),
        ),
    ]
