# Generated by Django 2.1 on 2019-07-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190712_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='customergroup',
            name='state',
            field=models.SmallIntegerField(choices=[(0, '待解析'), (1, '已解析'), (2, '已删除')], db_index=True, default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='customergroup',
            name='uuid',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='收件人列表ID'),
        ),
    ]
