# Generated by Django 2.1 on 2019-07-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190719_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='topproduct',
            name='store_id',
            field=models.IntegerField(db_index=True, default=1, verbose_name='店铺id'),
            preserve_default=False,
        ),
    ]
