# Generated by Django 2.1 on 2019-08-31 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_store_op_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'managed': True, 'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'managed': False},
        ),
    ]
