# Generated by Django 2.1 on 2019-08-19 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190819_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'managed': False, 'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'managed': True},
        ),
    ]
