# Generated by Django 2.1 on 2019-07-11 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_store_hmac'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='customer_shop',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='customer_shop'),
        ),
        migrations.AddField(
            model_name='store',
            name='letter_domain',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='letter_domain'),
        ),
        migrations.AddField(
            model_name='store',
            name='message_domain',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='message_domain'),
        ),
        migrations.AddField(
            model_name='store',
            name='news_domain',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='news_domain'),
        ),
        migrations.AddField(
            model_name='store',
            name='sender',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='sender'),
        ),
        migrations.AddField(
            model_name='store',
            name='shop_alias',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='your shop'),
        ),
    ]
