# Generated by Django 2.1 on 2019-08-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190808_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='store_id',
            field=models.IntegerField(db_index=True, default=1, verbose_name='店铺id'),
            preserve_default=False,
        ),
    ]
