# Generated by Django 2.1 on 2019-07-12 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190712_1840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='customergroup',
            options={'managed': False},
        ),
    ]
