# Generated by Django 2.1 on 2019-08-08 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_product_store_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('store_id', 'uuid')},
        ),
    ]
