# Generated by Django 2.1 on 2019-08-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190819_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='currency',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='currency'),
        ),
    ]
