# Generated by Django 2.1 on 2019-08-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190831_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='email_trigger_id',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True, verbose_name='email_trigger_id'),
        ),
    ]
