# Generated by Django 2.1 on 2019-07-19 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_topproduct_store_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customergroup',
            options={},
        ),
        migrations.RemoveField(
            model_name='topproduct',
            name='store_id',
        ),
        migrations.AddField(
            model_name='topproduct',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Store'),
            preserve_default=False,
        ),
    ]
