# Generated by Django 2.1 on 2019-09-02 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_emailtemplate_email_trigger_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboard',
            options={},
        ),
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'managed': False, 'ordering': ['-id']},
        ),
    ]
