# Generated by Django 2.1 on 2019-08-09 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190808_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'managed': True, 'ordering': ['-id']},
        ),
    ]
