# Generated by Django 2.1 on 2019-08-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_store_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='site_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='site_name'),
        ),
    ]
