# Generated by Django 2.1 on 2019-09-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190902_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='delta_click',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Click 增量'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='delta_open',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Open 增量'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='delta_sent',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Sent 增量'),
        ),
    ]
