# Generated by Django 2.1 on 2019-07-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190712_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='first_name'),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='last_name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='payment_amount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='客户付款金额'),
        ),
    ]
