# Generated by Django 2.1 on 2019-08-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_store_site_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='emailtask',
            name='store_id',
            field=models.IntegerField(db_index=True, default=1, verbose_name='店铺id'),
            preserve_default=False,
        ),
    ]
