# Generated by Django 2.1 on 2019-07-19 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190719_1800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customergroup',
            options={},
        ),
    ]
