# Generated by Django 2.1 on 2019-08-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190809_1755'),
    ]

    operations = [
    ]
