# Generated by Django 2.1 on 2019-07-11 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_store_store_view_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriberActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opt_time', models.DateTimeField(blank=True, null=True, verbose_name='客户登陆时间')),
                ('email', models.CharField(db_index=True, max_length=255, verbose_name='客户邮件地址')),
                ('message_uuid', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='关联的邮件ID')),
                ('type', models.SmallIntegerField(default=0, verbose_name='客户操作类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Store')),
            ],
            options={
                'db_table': 'subscriber_activity',
            },
        ),
        migrations.RemoveField(
            model_name='customer',
            name='clicked_email_times',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_click_email_time',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_opened_email_time',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='opened_email_times',
        ),
        migrations.AddField(
            model_name='customergroup',
            name='clicks',
            field=models.IntegerField(default=0, verbose_name='点击量'),
        ),
        migrations.AddField(
            model_name='customergroup',
            name='opens',
            field=models.IntegerField(default=0, verbose_name='打开量'),
        ),
        migrations.AddField(
            model_name='customergroup',
            name='sents',
            field=models.IntegerField(default=0, verbose_name='发送量'),
        ),
        migrations.AddField(
            model_name='customergroup',
            name='uuid',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='用户列表ID'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='click_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='邮件单击率'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='clicks',
            field=models.IntegerField(default=0, verbose_name='点击量'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='open_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='邮件打开率'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='opens',
            field=models.IntegerField(default=0, verbose_name='打开量'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='sents',
            field=models.IntegerField(default=0, verbose_name='发送量'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='unsubscribe_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='邮件退订率'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='unsubscribes',
            field=models.IntegerField(default=0, verbose_name='退订量'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='uuid',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='邮件ID'),
        ),
        migrations.AlterField(
            model_name='customergroup',
            name='click_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='邮件单击率'),
        ),
        migrations.AlterField(
            model_name='customergroup',
            name='open_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='邮件打开率'),
        ),
        migrations.AlterUniqueTogether(
            name='subscriberactivity',
            unique_together={('opt_time', 'email', 'type')},
        ),
    ]
