# Generated by Django 2.1 on 2019-08-19 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190819_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtask',
            options={'managed': False},
        ),
    ]
