# Generated by Django 2.1 on 2019-09-02 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190902_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard',
            old_name='delta_click',
            new_name='clicks',
        ),
        migrations.RenameField(
            model_name='dashboard',
            old_name='delta_open',
            new_name='opens',
        ),
        migrations.RenameField(
            model_name='dashboard',
            old_name='delta_sent',
            new_name='sents',
        ),
    ]
