# Generated by Django 2.1 on 2019-08-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20190809_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='banner',
            field=models.CharField(default='', max_length=255, verbose_name='邮件banner'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='logo',
            field=models.CharField(default='', max_length=255, verbose_name='邮件logo'),
        ),
    ]
