# Generated by Django 2.1 on 2019-07-20 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20190719_1800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customergroup',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='orderevent',
            options={},
        ),
    ]
