# Generated by Django 2.1 on 2019-09-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20190902_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='dashboard',
            name='repeat_customers',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='订单超过2个的用户数'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='total_customers',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='总的客户数'),
        ),
    ]
