# Generated by Django 2.1 on 2019-07-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20190711_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='customer_email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='customer_email'),
        ),
    ]
