# Generated by Django 2.1 on 2019-07-15 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20190715_1003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customergroup',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='emailtrigger',
            options={},
        ),
    ]
