# Generated by Django 2.1 on 2019-09-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20190902_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkoutevent',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='customergroup',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='customerunsubscribe',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='dashboard',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='emailrecord',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='emailtask',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'managed': True, 'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='emailtrigger',
            options={'managed': True, 'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='orderevent',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='subscriberactivity',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='topproduct',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='用户唯一标识'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=64, null=True, verbose_name='账户邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=64, unique=True, verbose_name='账户'),
        ),
    ]
