# Generated by Django 2.1 on 2019-08-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20190809_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='source',
            field=models.SmallIntegerField(choices=[(0, 'opstores'), (1, 'smartsend'), (2, 'all')], db_index=True, default=1, verbose_name='状态'),
        ),
    ]
