# Generated by Django 2.1 on 2019-07-15 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20190715_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtrigger',
            options={'managed': False},
        ),
    ]
