# Generated by Django 2.1 on 2019-09-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20190909_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutevent',
            name='cart_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='cart_token'),
        ),
        migrations.AlterField(
            model_name='checkoutevent',
            name='checkout_id',
            field=models.CharField(db_index=True, max_length=64, verbose_name='checkout的唯一标识符'),
        ),
        migrations.AlterField(
            model_name='checkoutevent',
            name='customer_uuid',
            field=models.CharField(db_index=True, max_length=64, verbose_name='订单对应客户id'),
        ),
        migrations.AlterField(
            model_name='checkoutevent',
            name='total_price',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='订单总金额'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=64, null=True, verbose_name='客户邮箱'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='last_name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_order_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='last_order_id'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='payment_amount',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='客户付款金额'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='uuid',
            field=models.CharField(db_index=True, max_length=64, verbose_name='客户的唯一id'),
        ),
        migrations.AlterField(
            model_name='customergroup',
            name='uuid',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='收件人列表ID'),
        ),
        migrations.AlterField(
            model_name='customerunsubscribe',
            name='email',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='客户的email'),
        ),
        migrations.AlterField(
            model_name='emailrecord',
            name='uuid',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='邮件ID'),
        ),
        migrations.AlterField(
            model_name='emailtask',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '待发送'), (1, '已发送(成功)'), (2, '已发送但发送失败'), (3, '模版禁用'), (4, '模板已删除'), (5, '重复发送人员')], db_index=True, default=0, verbose_name='邮件发送状态'),
        ),
        migrations.AlterField(
            model_name='emailtask',
            name='uuid',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='事务邮件ID'),
        ),
        migrations.AlterField(
            model_name='emailtrigger',
            name='customer_list_id',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='flows筛选出来的ListId'),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='checkout_id',
            field=models.CharField(db_index=True, max_length=64, verbose_name='checkout的唯一标识符'),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='customer_uuid',
            field=models.CharField(db_index=True, max_length=64, verbose_name='订单对应客户id'),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='event_uuid',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='事件的唯一标识符'),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='order_uuid',
            field=models.CharField(max_length=64, verbose_name='订单的唯一标识符'),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='status_tag',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='订单类型tag'),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='total_price',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='订单总金额'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=128, verbose_name='产品名称'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='产品价格'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='category_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='产品类目id'),
        ),
        migrations.AlterField(
            model_name='store',
            name='currency',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='store',
            name='customer_shop',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='customer_shop'),
        ),
        migrations.AlterField(
            model_name='store',
            name='domain',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='店铺domain'),
        ),
        migrations.AlterField(
            model_name='store',
            name='email',
            field=models.EmailField(blank=True, max_length=64, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='store',
            name='hmac',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='hmac'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='店铺名称'),
        ),
        migrations.AlterField(
            model_name='store',
            name='op_user',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='opstore用户'),
        ),
        migrations.AlterField(
            model_name='store',
            name='sender',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='sender'),
        ),
        migrations.AlterField(
            model_name='store',
            name='sender_address',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='customer_email'),
        ),
        migrations.AlterField(
            model_name='store',
            name='service_email',
            field=models.EmailField(blank=True, max_length=64, null=True, verbose_name='service_email'),
        ),
        migrations.AlterField(
            model_name='store',
            name='site_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='site_name'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_view_id',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='店铺的GA中的view id'),
        ),
        migrations.AlterField(
            model_name='store',
            name='timezone',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='店铺的时区'),
        ),
        migrations.AlterField(
            model_name='store',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='账号使用标识'),
        ),
        migrations.AlterField(
            model_name='store',
            name='url',
            field=models.CharField(blank=True, db_index=True, max_length=64, unique=True, verbose_name='店铺URL'),
        ),
        migrations.AlterField(
            model_name='subscriberactivity',
            name='email',
            field=models.CharField(db_index=True, max_length=64, verbose_name='客户邮件地址'),
        ),
    ]
