# Generated by Django 2.1 on 2019-07-20 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20190720_1121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderevent',
            options={'managed': False},
        ),
    ]
