# Generated by Django 2.1 on 2019-07-15 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20190715_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
