# Generated by Django 2.1 on 2019-08-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_emailtemplate_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtrigger',
            options={'managed': True, 'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='source',
            field=models.SmallIntegerField(choices=[(0, 'opstores'), (1, 'smartsend'), (2, 'all')], db_index=True, default=1, verbose_name='平台模板'),
        ),
    ]
