# Generated by Django 2.1 on 2019-07-20 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20190720_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={},
        ),
    ]
