# Generated by Django 2.1 on 2019-08-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20190809_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtrigger',
            options={'managed': False, 'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='product_condition',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='邮件body_text'),
        ),
    ]
