# Generated by Django 2.1 on 2019-07-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20190720_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='product_list',
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='top_type',
            field=models.TextField(default='x', verbose_name='选择的哪类top product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='store_id',
            field=models.IntegerField(db_index=True, verbose_name='店铺id'),
        ),
    ]
