# Generated by Django 2.1 on 2019-07-15 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20190715_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='subscriberactivity',
            options={},
        ),
    ]
