# Generated by Django 2.1 on 2019-08-12 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20190812_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'managed': False, 'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='emailtrigger',
            options={'managed': True, 'ordering': ['-id']},
        ),
    ]
