# Generated by Django 2.1 on 2019-07-15 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20190715_1456'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriberactivity',
            unique_together={('opt_time', 'email', 'type', 'message_uuid')},
        ),
    ]
