# Generated by Django 2.1 on 2019-08-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20190812_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtrigger',
            name='source',
            field=models.SmallIntegerField(choices=[(0, 'opstores'), (1, 'smartsend'), (2, 'all')], db_index=True, default=1, verbose_name='平台模板'),
        ),
    ]
