# Generated by Django 2.1 on 2019-07-15 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20190715_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subscriberactivity',
            options={'managed': False},
        ),
    ]
