# Generated by Django 2.1 on 2019-07-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20190720_1459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'ordering': ['update_time']},
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='top_type',
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='product_list',
            field=models.TextField(default='x', verbose_name='产品列表'),
            preserve_default=False,
        ),
    ]
