# Generated by Django 2.1 on 2019-07-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20190720_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='title',
            field=models.CharField(db_index=True, default='x', max_length=255, verbose_name='标题'),
            preserve_default=False,
        ),
    ]
