# Generated by Django 2.1 on 2019-07-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20190715_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='send_type',
            field=models.SmallIntegerField(choices=[(0, '定时邮件'), (1, '触发邮件')], db_index=True, default=0, verbose_name='邮件模板发送类型'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='banner',
            field=models.TextField(verbose_name='邮件banner'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='body_text',
            field=models.TextField(verbose_name='邮件body_text'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='customer_group_list',
            field=models.TextField(blank=True, null=True, verbose_name='邮件对应的客户组列表'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='heading_text',
            field=models.TextField(verbose_name='邮件'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='headline',
            field=models.TextField(verbose_name='邮件headline'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='logo',
            field=models.TextField(verbose_name='邮件logo'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='product_list',
            field=models.TextField(verbose_name='产品列表'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='send_rule',
            field=models.TextField(verbose_name='发送邮件规则'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='state',
            field=models.SmallIntegerField(choices=[(0, '待解析'), (1, '已解析'), (2, '已删除')], db_index=True, default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='subject',
            field=models.TextField(verbose_name='邮件标题'),
        ),
    ]
