# Generated by Django 2.1 on 2019-07-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20190715_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='邮件ID')),
                ('customer_group_list', models.TextField(blank=True, verbose_name='邮件对应的客户组列表')),
                ('sents', models.IntegerField(blank=True, null=True, verbose_name='发送量')),
                ('opens', models.IntegerField(blank=True, null=True, verbose_name='打开量')),
                ('clicks', models.IntegerField(blank=True, null=True, verbose_name='点击量')),
                ('unsubscribes', models.IntegerField(blank=True, null=True, verbose_name='退订量')),
                ('open_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='邮件打开率')),
                ('click_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='邮件单击率')),
                ('unsubscribe_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='邮件退订率')),
                ('store_id', models.IntegerField(verbose_name='店铺id')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'email_record',
            },
        ),
        migrations.CreateModel(
            name='SalesVolume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('three_val', models.TextField(blank=True, null=True, verbose_name='前三天的销售量')),
                ('seven_val', models.TextField(blank=True, null=True, verbose_name='前七天的销售量')),
                ('fifteen_val', models.TextField(blank=True, null=True, verbose_name='前十五天的销售量')),
                ('thirty_val', models.TextField(blank=True, null=True, verbose_name='前三十天的销售量')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'sales_volume',
            },
        ),
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'managed': False},
        ),
    ]
