# Generated by Django 2.1 on 2019-08-13 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_emailtemplate_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'managed': False, 'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='emailtrigger',
            options={'managed': True, 'ordering': ['-id']},
        ),
    ]
