# Generated by Django 2.1 on 2019-08-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20190813_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtrigger',
            name='source',
        ),
        migrations.AddField(
            model_name='emailtrigger',
            name='is_open',
            field=models.SmallIntegerField(choices=[(0, 'internal'), (1, 'external')], db_index=True, default=0, verbose_name='是否对外'),
        ),
    ]
