# Generated by Django 2.1 on 2019-07-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20190715_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=255, verbose_name='购物车事件的唯一标识符')),
                ('store', models.CharField(max_length=255, verbose_name='事件对应的店铺的url')),
                ('customer', models.CharField(db_index=True, max_length=255, verbose_name='订单对应客户id')),
                ('products', models.TextField(blank=True, null=True, verbose_name="所涉及到的产品id列表, eg:['121213']")),
                ('create_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'cart_event',
            },
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=255, verbose_name='订单事件的唯一标识符')),
                ('status', models.IntegerField(default=0, verbose_name='订单事件类型, 0-创建(未支付)，1-支付')),
                ('store', models.CharField(max_length=255, verbose_name='订单对应的店铺的url')),
                ('customer', models.CharField(db_index=True, max_length=255, verbose_name='订单对应客户id')),
                ('products', models.TextField(blank=True, null=True, verbose_name='订单所涉及到的产品及其销量信息')),
                ('create_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='订单创建时间')),
            ],
            options={
                'db_table': 'order_event',
            },
        ),
        migrations.AlterModelOptions(
            name='emailrecord',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='salesvolume',
            options={'managed': False},
        ),
    ]
