# Generated by Django 2.1 on 2019-07-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20190720_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='产品价格'),
        ),
    ]
