# Generated by Django 2.1 on 2019-07-20 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False},
        ),
    ]
