# Generated by Django 2.1 on 2019-07-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20190717_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='uuid',
            field=models.CharField(db_index=True, default=1, max_length=255, verbose_name='客户的唯一id'),
            preserve_default=False,
        ),
    ]
