# Generated by Django 2.1 on 2019-08-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20190813_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='banner',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='邮件banner'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='logo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='邮件logo'),
        ),
    ]
