# Generated by Django 2.1 on 2019-07-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20190722_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='state',
            field=models.SmallIntegerField(default=0, verbose_name='前端判断是否勾选状态'),
        ),
    ]
