# Generated by Django 2.1 on 2019-07-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_customer_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='store',
            name='url',
            field=models.CharField(blank=True, db_index=True, max_length=255, unique=True, verbose_name='店铺URL'),
        ),
    ]
