# Generated by Django 2.1 on 2019-08-13 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20190813_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'managed': False, 'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='emailtrigger',
            options={'managed': True, 'ordering': ['-id']},
        ),
    ]
