# Generated by Django 2.1 on 2019-07-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_product_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtrigger',
            options={'managed': False, 'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='html',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='send_type',
            field=models.SmallIntegerField(choices=[(0, '定时邮件'), (1, '触发邮件'), (3, '测试邮件')], db_index=True, default=0, verbose_name='邮件模板发送类型'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='标题'),
        ),
    ]
