# Generated by Django 2.1 on 2019-07-17 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20190717_1050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartevent',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='orderevent',
            options={'managed': False},
        ),
    ]
