# Generated by Django 2.1 on 2019-08-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20190813_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtrigger',
            name='draft',
            field=models.SmallIntegerField(choices=[(0, '线上'), (1, '草稿')], db_index=True, default=0, verbose_name='是否是草稿状态'),
        ),
    ]
