# Generated by Django 2.1 on 2019-07-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20190722_1447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'managed': False, 'ordering': ['update_time']},
        ),
        migrations.RemoveField(
            model_name='store',
            name='customer_init',
        ),
        migrations.RemoveField(
            model_name='store',
            name='order_init',
        ),
        migrations.AddField(
            model_name='store',
            name='init',
            field=models.SmallIntegerField(choices=[(0, '新店铺'), (1, '旧店铺')], db_index=True, default=0, verbose_name='店铺初始化'),
        ),
    ]
