# Generated by Django 2.1 on 2019-08-15 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_emailtrigger_draft'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='emailtrigger',
            options={'managed': False, 'ordering': ['-id']},
        ),
    ]
