# Generated by Django 2.1 on 2019-07-23 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20190723_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.SmallIntegerField(choices=[(0, '待发送'), (1, '已发送(成功)'), (2, '模板已删除'), (3, '已发送但发送失败')], db_index=True, default=0, verbose_name='邮件发送状态')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('execute_time', models.DateTimeField(db_index=True, verbose_name='执行时间')),
                ('finished_time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.EmailTemplate')),
            ],
            options={
                'db_table': 'email_task',
            },
        ),
    ]
