# Generated by Django 2.1 on 2019-07-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20190717_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartevent',
            options={},
        ),
        migrations.RenameField(
            model_name='orderevent',
            old_name='customer',
            new_name='customer_uuid',
        ),
        migrations.RenameField(
            model_name='orderevent',
            old_name='products',
            new_name='product_info',
        ),
        migrations.RenameField(
            model_name='orderevent',
            old_name='store',
            new_name='store_url',
        ),
        migrations.RemoveField(
            model_name='orderevent',
            name='uri',
        ),
        migrations.AddField(
            model_name='orderevent',
            name='event_uuid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='事件的唯一标识符'),
        ),
        migrations.AddField(
            model_name='orderevent',
            name='order_uuid',
            field=models.CharField(default='2018-07-01 00:00:00', max_length=255, verbose_name='订单的唯一标识符'),
            preserve_default=False,
        ),
    ]
