# Generated by Django 2.1 on 2019-08-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20190815_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='is_cart',
            field=models.SmallIntegerField(choices=[(0, '不显示'), (1, '显示')], db_index=True, default=0, verbose_name='是否显示购物车产品'),
        ),
    ]
