# Generated by Django 2.1 on 2019-08-15 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_emailtemplate_is_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'managed': False, 'ordering': ['-id']},
        ),
    ]
