# Generated by Django 2.1 on 2019-07-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20190717_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartevent',
            old_name='customer',
            new_name='customer_uuid',
        ),
        migrations.RenameField(
            model_name='cartevent',
            old_name='uri',
            new_name='event_uuid',
        ),
        migrations.RenameField(
            model_name='cartevent',
            old_name='products',
            new_name='product_list',
        ),
        migrations.RenameField(
            model_name='cartevent',
            old_name='store',
            new_name='store_url',
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='status',
            field=models.IntegerField(db_index=True, default=0, verbose_name='订单事件类型, 0-创建(未支付)，1-支付'),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='store_url',
            field=models.CharField(db_index=True, max_length=255, verbose_name='订单对应的店铺的url'),
        ),
    ]
