# Generated by Django 2.1 on 2019-07-17 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20190717_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailrecord',
            options={},
        ),
    ]
