# Generated by Django 2.1 on 2019-07-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20190723_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard',
            old_name='click_rate',
            new_name='avg_click_rate',
        ),
        migrations.RenameField(
            model_name='dashboard',
            old_name='open_rate',
            new_name='avg_open_rate',
        ),
        migrations.RenameField(
            model_name='dashboard',
            old_name='total_unsubscribe_rate',
            new_name='avg_unsubscribe_rate',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='sent',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='total_click_rate',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='total_open_rate',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='unsubscribe_rate',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='total_click',
            field=models.IntegerField(blank=True, null=True, verbose_name='Click总量'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='total_open',
            field=models.IntegerField(blank=True, null=True, verbose_name='Open总量'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='store_id',
            field=models.IntegerField(db_index=True, verbose_name='店铺id'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='total_sent',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sent总量'),
        ),
    ]
