# Generated by Django 2.1 on 2019-08-15 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20190815_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtask',
            options={'managed': True},
        ),
    ]
