# Generated by Django 2.1 on 2019-07-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20190723_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='total_unsubscribe',
            field=models.IntegerField(blank=True, null=True, verbose_name='Unsubscribe总量'),
        ),
    ]
