# Generated by Django 2.1 on 2019-08-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20190815_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtask',
            name='template',
        ),
        migrations.AddField(
            model_name='emailtask',
            name='template_id',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True, verbose_name='email_template_id'),
        ),
        migrations.AlterField(
            model_name='emailtask',
            name='email_trigger_id',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True, verbose_name='email_trigger_id'),
        ),
    ]
