# Generated by Django 2.1 on 2019-07-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20190717_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailrecord',
            name='customer_group_list',
        ),
        migrations.AddField(
            model_name='emailrecord',
            name='email_template_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='模版id'),
        ),
    ]
