# Generated by Django 2.1 on 2019-07-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20190717_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailrecord',
            options={'managed': False},
        ),
        # migrations.RemoveField(
        #     model_name='cartevent',
        #     name='store_url',
        # ),
        # migrations.RemoveField(
        #     model_name='orderevent',
        #     name='store_url',
        # ),
        migrations.AddField(
            model_name='cartevent',
            name='store_id',
            field=models.IntegerField(default='3', verbose_name='店铺id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderevent',
            name='store_id',
            field=models.IntegerField(default='3', verbose_name='店铺id'),
            preserve_default=False,
        ),
    ]
