# Generated by Django 2.1 on 2019-08-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20190816_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='product_title',
            field=models.TextField(blank=True, null=True, verbose_name='产品标题'),
        ),
    ]
