# Generated by Django 2.1 on 2019-07-23 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20190723_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboard',
            options={'managed': False},
        ),
    ]
