# Generated by Django 2.1 on 2019-07-17 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20190717_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customergroup',
            options={},
        ),
        migrations.RemoveField(
            model_name='cartevent',
            name='store_url',
        ),
        migrations.RemoveField(
            model_name='orderevent',
            name='store_url',
        ),
    ]
