# Generated by Django 2.1 on 2019-07-17 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20190717_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartevent',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customergroup',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='orderevent',
            options={'managed': False},
        ),
    ]
