# Generated by Django 2.1 on 2019-07-23 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20190723_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='store_id',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='session',
            field=models.IntegerField(blank=True, null=True, verbose_name='session'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Store'),
            preserve_default=False,
        ),
    ]
