# Generated by Django 2.1 on 2019-07-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20190723_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='conversion_rate',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='repeat_purchase_rate',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='store',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='store_id',
            field=models.IntegerField(db_index=True, default=1, verbose_name='店铺id'),
            preserve_default=False,
        ),
    ]
