# Generated by Django 2.1 on 2019-07-17 19:43

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20190717_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderevent',
            name='product_info',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True, verbose_name='订单所涉及到的产品及其销量信息'),
        ),
        migrations.AlterUniqueTogether(
            name='orderevent',
            unique_together={('store_id', 'order_uuid')},
        ),
    ]
