# Generated by Django 2.1 on 2019-07-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20190723_1725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboard',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='store',
            name='store_create_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='店铺创建时间'),
        ),
        migrations.AlterField(
            model_name='store',
            name='update_time',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间'),
        ),
    ]
