# Generated by Django 2.1 on 2019-07-24 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20190724_1055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboard',
            options={},
        ),
    ]
