# Generated by Django 2.1 on 2019-07-17 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20190717_1943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderevent',
            options={'managed': False},
        ),
    ]
