# Generated by Django 2.1 on 2019-07-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20190724_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='update_time',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间'),
        ),
    ]
