# Generated by Django 2.1 on 2019-07-17 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20190717_1955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderevent',
            options={},
        ),
    ]
