# Generated by Django 2.1 on 2019-07-24 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20190724_1056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboard',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
