# Generated by Django 2.1 on 2019-07-17 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20190717_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderevent',
            options={'managed': False},
        ),
    ]
