# Generated by Django 2.1 on 2019-07-17 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20190717_2004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderevent',
            options={},
        ),
    ]
