# Generated by Django 2.1 on 2019-07-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20190724_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='update_time',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间'),
        ),
    ]
