# Generated by Django 2.1 on 2019-07-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_auto_20190717_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderevent',
            name='order_create_time',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='订单创建时间'),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='create_time',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='创建时间'),
        ),
    ]
