# Generated by Django 2.1 on 2019-07-25 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_auto_20190724_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailrecord',
            options={},
        ),
        migrations.AlterModelOptions(
            name='emailtrigger',
            options={'ordering': ['-id']},
        ),
    ]
