# Generated by Django 2.1 on 2019-07-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20190725_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtrigger',
            name='members',
        ),
        migrations.RemoveField(
            model_name='emailtrigger',
            name='trigger_info',
        ),
        migrations.AddField(
            model_name='emailrecord',
            name='email_trigger_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='邮件触发器id'),
        ),
        migrations.AddField(
            model_name='emailtrigger',
            name='customer_list',
            field=models.TextField(blank=True, null=True, verbose_name='对应客户列表'),
        ),
        migrations.AddField(
            model_name='emailtrigger',
            name='note',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='对应Note'),
        ),
        migrations.AddField(
            model_name='emailtrigger',
            name='relation_info',
            field=models.TextField(blank=True, null=True, verbose_name='筛选条件'),
        ),
        migrations.AddField(
            model_name='emailtrigger',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='对应的销售额'),
        ),
        migrations.AddField(
            model_name='emailtrigger',
            name='type',
            field=models.SmallIntegerField(default=0, verbose_name='邮件类型'),
        ),
        migrations.AlterField(
            model_name='emailtrigger',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
    ]
