# Generated by Django 2.1 on 2019-07-17 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20190717_2005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='orderevent',
            options={'managed': False},
        ),
    ]
