# Generated by Django 2.1 on 2019-07-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_auto_20190725_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtrigger',
            options={'managed': False, 'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='emailrecord',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='对应的销售额'),
        ),
    ]
