# Generated by Django 2.1 on 2019-07-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_auto_20190717_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_order_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='last_order_id'),
        ),
        migrations.AddField(
            model_name='customer',
            name='orders_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='订单数量'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('store_id', 'uuid')},
        ),
    ]
