# Generated by Django 2.1 on 2019-07-26 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_auto_20190726_1017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'ordering': ['update_time']},
        ),
        migrations.RemoveField(
            model_name='emailrecord',
            name='revenue',
        ),
    ]
