# Generated by Django 2.1 on 2019-07-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_auto_20190726_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='对应的销售额'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='sessions',
            field=models.IntegerField(default=0, verbose_name='流量数'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='transcations',
            field=models.IntegerField(default=0, verbose_name='交易次数'),
        ),
    ]
