# Generated by Django 2.1 on 2019-07-26 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_auto_20190726_1029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailrecord',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'managed': False, 'ordering': ['update_time']},
        ),
        migrations.AddField(
            model_name='emailtask',
            name='customer_list',
            field=models.TextField(blank=True, null=True, verbose_name='符合触发条件的用户列表'),
        ),
        migrations.AddField(
            model_name='emailtask',
            name='email_trigger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.EmailTrigger'),
        ),
        migrations.AddField(
            model_name='emailtask',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Timed mail'), (1, 'Trigger mail')], db_index=True, default=0, verbose_name='邮件类型'),
        ),
        migrations.AlterField(
            model_name='emailtask',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.EmailTemplate'),
        ),
    ]
