# Generated by Django 2.1 on 2019-07-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_auto_20190729_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='unsubscribe_date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='取消订阅时间'),
        ),
        migrations.AddField(
            model_name='customer',
            name='unsubscribe_status',
            field=models.SmallIntegerField(choices=[(0, 'is false'), (1, 'is true')], db_index=True, default=0, verbose_name='取消订阅'),
        ),
    ]
