# Generated by Django 2.1 on 2019-07-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_auto_20190730_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtrigger',
            name='note',
            field=models.TextField(default='[]', verbose_name='对应Note列表'),
        ),
    ]
