# Generated by Django 2.1 on 2019-07-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_auto_20190730_1109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkoutevent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='emailtask',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='topproduct',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='orderevent',
            name='checkout_id',
            field=models.CharField(db_index=True, default=1, max_length=255, verbose_name='checkout的唯一标识符'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='store_id',
            field=models.IntegerField(db_index=True, verbose_name='店铺id'),
        ),
    ]
