# Generated by Django 2.1 on 2019-07-30 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_auto_20190730_1109'),
        ('app', '0053_auto_20190730_1115'),
    ]

    operations = [
    ]
