# Generated by Django 2.1 on 2019-07-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_merge_20190730_1125'),
    ]

    operations = [
    ]
