# Generated by Django 2.1 on 2019-07-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_auto_20190730_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderevent',
            name='checkout_id',
            field=models.CharField(db_index=True, default=1, max_length=255, verbose_name='checkout的唯一标识符'),
            preserve_default=False,
        ),
    ]
