# Generated by Django 2.1 on 2019-07-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_orderevent_checkout_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtrigger',
            options={'managed': False, 'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='topproduct',
            options={'managed': False},
        ),
        migrations.RemoveField(
            model_name='emailtask',
            name='email_trigger',
        ),
        migrations.AddField(
            model_name='emailtask',
            name='email_trigger_id',
            field=models.IntegerField(db_index=True, default=1, verbose_name='email_trigger_id'),
            preserve_default=False,
        )
    ]
