# Generated by Django 2.1 on 2019-07-30 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_auto_20190730_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtask',
            name='template',
        ),
        migrations.DeleteModel(
            name='EmailTask',
        ),
    ]
