# Generated by Django 2.1 on 2019-07-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_auto_20190730_1138'),
    ]

    operations = [
    ]
