# Generated by Django 2.1 on 2019-07-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_auto_20190730_1139'),
    ]

    operations = [
    ]
