# Generated by Django 2.1 on 2019-07-30 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_auto_20190730_1141'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderevent',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='orderevent',
            name='store_id',
        ),
    ]
