# Generated by Django 2.1 on 2019-07-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_auto_20190730_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderevent',
            name='store_id',
            field=models.IntegerField(db_index=True, default=1, verbose_name='店铺id'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='orderevent',
            unique_together={('store_id', 'order_uuid')},
        ),
    ]
