# Generated by Django 2.1 on 2019-07-30 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_auto_20190730_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkoutevent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='emailtask',
            options={'managed': False},
        ),
    ]
