# Generated by Django 2.1 on 2019-07-30 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_auto_20190730_1341'),
    ]

    operations = [

    ]
