# Generated by Django 2.1 on 2019-07-30 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_delete_checkoutevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkoutevent',
            options={'managed': False},
        ),
    ]
