# Generated by Django 2.1 on 2019-07-30 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_auto_20190730_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkoutevent',
            options={},
        ),
    ]
