# Generated by Django 2.1 on 2019-07-30 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_auto_20190730_1349'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckoutEvent',
        ),
    ]
