# Generated by Django 2.1 on 2019-07-30 13:51

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_delete_checkoutevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_uuid', models.CharField(max_length=255, verbose_name='checkout事件的唯一标识符')),
                ('checkout_id', models.CharField(max_length=255, verbose_name='checkout的唯一标识符')),
                ('customer_uuid', models.CharField(db_index=True, max_length=255, verbose_name='订单对应客户id')),
                ('product_list', models.TextField(blank=True, null=True, verbose_name="所涉及到的产品id列表, eg:['121213']")),
                ('product_info', django_mysql.models.JSONField(blank=True, default=dict, null=True, verbose_name='订单所涉及到的产品及其销量信息')),
                ('total_price', models.CharField(blank=True, max_length=255, null=True, verbose_name='订单总金额')),
                ('checkout_create_time', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='订单创建时间')),
                ('checkout_update_time', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='订单更新时间')),
                ('store_id', models.IntegerField(db_index=True, verbose_name='店铺id')),
                ('create_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'checkout_event',
            },
        ),
    ]
