# Generated by Django 2.1 on 2019-07-30 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_auto_20190730_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkoutevent',
            options={},
        ),
    ]
