# Generated by Django 2.1 on 2019-07-30 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0073_auto_20190730_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutevent',
            name='store_id',
        ),
        migrations.AddField(
            model_name='checkoutevent',
            name='abandoned_checkout_url',
            field=models.TextField(blank=True, null=True, verbose_name='checkout_url'),
        ),
        migrations.AddField(
            model_name='checkoutevent',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Store'),
            preserve_default=False,
        ),
    ]
