# Generated by Django 2.1 on 2019-07-30 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_auto_20190730_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutevent',
            name='store',
        ),
    ]
