# Generated by Django 2.1 on 2019-07-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0075_remove_checkoutevent_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutevent',
            name='store_id',
            field=models.IntegerField(db_index=True, default=1, verbose_name='店铺id'),
            preserve_default=False,
        ),
    ]
