# Generated by Django 2.1 on 2019-07-30 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0076_checkoutevent_store_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutevent',
            name='product_list',
        ),
    ]
