# Generated by Django 2.1 on 2019-07-30 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0076_checkoutevent_store_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkoutevent',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='emailtask',
            options={},
        ),
    ]
