# Generated by Django 2.1 on 2019-07-30 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0077_remove_checkoutevent_product_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutevent',
            name='event_uuid',
        ),
    ]
