# Generated by Django 2.1 on 2019-07-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0077_auto_20190730_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtask',
            name='uuid',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='事务邮件ID'),
        ),
        migrations.AlterField(
            model_name='emailtask',
            name='email_trigger_id',
            field=models.IntegerField(db_index=True, default=None, verbose_name='email_trigger_id'),
        ),
    ]
