# Generated by Django 2.1 on 2019-07-30 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0078_auto_20190730_1743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkoutevent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='emailtask',
            options={'managed': False},
        ),
    ]
