# Generated by Django 2.1 on 2019-07-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0079_auto_20190730_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutevent',
            name='event_uuid',
        ),
        migrations.RemoveField(
            model_name='checkoutevent',
            name='product_list',
        ),
        migrations.AddField(
            model_name='checkoutevent',
            name='status',
            field=models.IntegerField(db_index=True, default=0, verbose_name='checkouts事件类型, 0-创建(未支付)，1-支付, 2-删除'),
        ),
    ]
