# Generated by Django 2.1 on 2019-07-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0080_auto_20190730_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutevent',
            name='checkout_id',
            field=models.CharField(db_index=True, max_length=255, verbose_name='checkout的唯一标识符'),
        ),
    ]
