# Generated by Django 2.1 on 2019-07-31 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0081_auto_20190731_1018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkoutevent',
            options={'managed': False},
        ),
    ]
