# Generated by Django 2.1 on 2019-07-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0083_auto_20190731_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutevent',
            name='email_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='最后一次邮件通知时间，为空代表还没有发送过促销邮件'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sign_up_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='客户登陆时间'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='unsubscribe_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='为真时代表休眠的截止日期'),
        ),
    ]
