# Generated by Django 2.1 on 2019-07-31 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0086_auto_20190731_1338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkoutevent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
    ]
