# Generated by Django 2.1 on 2019-07-31 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0088_auto_20190731_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkoutevent',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='emailtrigger',
            options={'ordering': ['-id']},
        ),
    ]
