# Generated by Django 2.1 on 2019-07-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0089_auto_20190731_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtrigger',
            name='customer_list_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='flows筛选出来的ListId'),
        ),
    ]
