# Generated by Django 2.1 on 2019-08-01 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0090_emailtrigger_customer_list_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkoutevent',
            options={},
        ),
        migrations.RemoveField(
            model_name='emailtrigger',
            name='store_id',
        ),
        migrations.AddField(
            model_name='emailtrigger',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Store'),
            preserve_default=False,
        ),
    ]
