# Generated by Django 2.1 on 2019-08-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0091_auto_20190801_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutevent',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
    ]
