# Generated by Django 2.1 on 2019-08-01 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0092_auto_20190801_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkoutevent',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='orderevent',
            options={},
        ),
    ]
