# Generated by Django 2.1 on 2019-08-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0095_auto_20190801_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtrigger',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='emailtrigger',
            name='store_id',
            field=models.IntegerField(db_index=True, verbose_name='店铺id'),
        ),
        migrations.AlterField(
            model_name='emailtrigger',
            name='update_time',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间'),
        ),
    ]
