# Generated by Django 2.1 on 2019-08-01 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0096_auto_20190801_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailtrigger',
            old_name='type',
            new_name='status',
        ),
    ]
