# Generated by Django 2.1 on 2019-08-01 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0097_auto_20190801_1037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboard',
            options={},
        ),
        migrations.AlterModelOptions(
            name='emailtrigger',
            options={'managed': False, 'ordering': ['-id']},
        ),
    ]
