# Generated by Django 2.1 on 2019-08-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0098_auto_20190801_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='orders',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Orders'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='revenue',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Revenue'),
        ),
    ]
