# Generated by Django 2.1 on 2019-08-01 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0099_auto_20190801_1108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtask',
            options={},
        ),
    ]
