# Generated by Django 2.1 on 2019-08-01 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0100_auto_20190801_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtask',
            name='email_trigger_id',
        ),
        migrations.RemoveField(
            model_name='emailtask',
            name='state',
        ),
        migrations.AddField(
            model_name='emailtask',
            name='email_trigger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.EmailTrigger'),
        ),
        migrations.AddField(
            model_name='emailtask',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '待发送'), (1, '已发送(成功)'), (2, '模板已删除'), (3, '已发送但发送失败'), (4, '模版禁用')], db_index=True, default=0, verbose_name='邮件发送状态'),
        ),
    ]
