# Generated by Django 2.1 on 2019-08-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0101_auto_20190801_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtask',
            name='email_trigger',
        ),
        migrations.AddField(
            model_name='emailtask',
            name='email_trigger_id',
            field=models.IntegerField(db_index=True, default=None, verbose_name='email_trigger_id'),
        ),
    ]
