# Generated by Django 2.1 on 2019-08-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0102_auto_20190801_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtask',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '待发送'), (1, '已发送(成功)'), (2, '已发送但发送失败'), (3, '模版禁用'), (4, '模板已删除')], db_index=True, default=0, verbose_name='邮件发送状态'),
        ),
    ]
