# Generated by Django 2.1 on 2019-08-01 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0103_auto_20190801_1134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtask',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='emailtrigger',
            options={'ordering': ['-id']},
        ),
    ]
