# Generated by Django 2.1 on 2019-08-01 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0104_auto_20190801_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'ordering': ['update_time']},
        ),
        migrations.AlterModelOptions(
            name='emailtrigger',
            options={'managed': False, 'ordering': ['-id']},
        ),
    ]
