# Generated by Django 2.1 on 2019-08-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0106_auto_20190801_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customergroup',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dashboard',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='emailrecord',
            options={},
        ),
        migrations.AlterModelOptions(
            name='emailtrigger',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='revenue',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=5, verbose_name='对应的销售额'),
        ),
    ]
