# Generated by Django 2.1 on 2019-08-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0107_auto_20190801_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customergroup',
            name='open_rate',
        ),
        migrations.RemoveField(
            model_name='emailrecord',
            name='open_rate',
        ),
        migrations.RemoveField(
            model_name='emailtrigger',
            name='open_rate',
        ),
        migrations.AlterField(
            model_name='customergroup',
            name='click_rate',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=5, verbose_name='邮件单击率'),
        ),
        migrations.AlterField(
            model_name='emailrecord',
            name='click_rate',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='邮件单击率'),
        ),
        migrations.AlterField(
            model_name='emailrecord',
            name='unsubscribe_rate',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='邮件退订率'),
        ),
        migrations.AlterField(
            model_name='emailtrigger',
            name='click_rate',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=5, verbose_name='邮件单击率'),
        ),
        migrations.AlterField(
            model_name='emailtrigger',
            name='revenue',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=5, verbose_name='对应的销售额'),
        ),
    ]
