# Generated by Django 2.1 on 2019-08-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0110_emailtrigger_open_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailrecord',
            name='open_rate',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='邮件打开率'),
        ),
    ]
