# Generated by Django 2.1 on 2019-08-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0111_emailrecord_open_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkoutevent',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='customergroup',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='dashboard',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='emailrecord',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='emailtask',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'managed': True, 'ordering': ['update_time']},
        ),
        migrations.AlterModelOptions(
            name='emailtrigger',
            options={'managed': True, 'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='orderevent',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='topproduct',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='customergroup',
            name='click_rate',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=8, verbose_name='邮件单击率'),
        ),
        migrations.AlterField(
            model_name='customergroup',
            name='open_rate',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=8, verbose_name='邮件打开率'),
        ),
        migrations.AlterField(
            model_name='emailrecord',
            name='click_rate',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True, verbose_name='邮件单击率'),
        ),
        migrations.AlterField(
            model_name='emailrecord',
            name='open_rate',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True, verbose_name='邮件打开率'),
        ),
        migrations.AlterField(
            model_name='emailrecord',
            name='unsubscribe_rate',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True, verbose_name='邮件退订率'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='revenue',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=8, verbose_name='对应的销售额'),
        ),
        migrations.AlterField(
            model_name='emailtrigger',
            name='click_rate',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=8, verbose_name='邮件单击率'),
        ),
        migrations.AlterField(
            model_name='emailtrigger',
            name='open_rate',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=8, verbose_name='邮件打开率'),
        ),
        migrations.AlterField(
            model_name='emailtrigger',
            name='revenue',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=8, verbose_name='对应的销售额'),
        ),
    ]
