# Generated by Django 2.1 on 2019-08-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0113_auto_20190802_1029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkoutevent',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='customergroup',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='dashboard',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='emailrecord',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='emailtask',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'managed': True, 'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='emailtrigger',
            options={'managed': True, 'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='orderevent',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='topproduct',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='revenue',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='对应的销售额'),
        ),
    ]
