# Generated by Django 2.1 on 2019-08-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0114_auto_20190802_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topproduct',
            name='store',
        ),
        migrations.AddField(
            model_name='topproduct',
            name='store_id',
            field=models.IntegerField(db_index=True, default=1, verbose_name='店铺id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customergroup',
            name='click_rate',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='邮件单击率'),
        ),
        migrations.AlterField(
            model_name='customergroup',
            name='open_rate',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='邮件打开率'),
        ),
        migrations.AlterField(
            model_name='emailrecord',
            name='click_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='邮件单击率'),
        ),
        migrations.AlterField(
            model_name='emailrecord',
            name='open_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='邮件打开率'),
        ),
        migrations.AlterField(
            model_name='emailrecord',
            name='unsubscribe_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='邮件退订率'),
        ),
        migrations.AlterField(
            model_name='emailtrigger',
            name='click_rate',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='邮件单击率'),
        ),
        migrations.AlterField(
            model_name='emailtrigger',
            name='open_rate',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='邮件打开率'),
        ),
        migrations.AlterField(
            model_name='emailtrigger',
            name='revenue',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='对应的销售额'),
        ),
    ]
