# Generated by Django 2.1 on 2019-08-02 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0116_auto_20190802_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboard',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'managed': False, 'ordering': ['-id']},
        ),
    ]
