# Generated by Django 2.1 on 2019-08-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0117_auto_20190802_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='total_sent',
            field=models.IntegerField(default=0, verbose_name='Sent总量'),
        ),
    ]
