# Generated by Django 2.1 on 2019-08-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0118_auto_20190802_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='total_orders',
            field=models.IntegerField(default=0, verbose_name='Orders'),
        ),
    ]
