# Generated by Django 2.1 on 2019-08-03 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0120_auto_20190803_0955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboard',
            options={'managed': True},
        ),
    ]
