# Generated by Django 2.1 on 2019-08-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0122_auto_20190803_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='avg_click_rate',
            field=models.FloatField(default=0, verbose_name='Click Rate'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='avg_conversion_rate',
            field=models.FloatField(default=0, verbose_name='Conversion Rate'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='avg_open_rate',
            field=models.FloatField(default=0, verbose_name='Open Rate'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='avg_repeat_purchase_rate',
            field=models.FloatField(default=0, verbose_name='Repeat Purchase Rate'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='avg_unsubscribe_rate',
            field=models.FloatField(default=0, verbose_name='Unsubscribe Rate'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='orders',
            field=models.IntegerField(default=0, verbose_name='Orders'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='revenue',
            field=models.FloatField(default=0, verbose_name='Revenue'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='session',
            field=models.IntegerField(default=0, verbose_name='session'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='total_click',
            field=models.IntegerField(default=0, verbose_name='Click总量'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='total_open',
            field=models.IntegerField(default=0, verbose_name='Open总量'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='total_sessions',
            field=models.IntegerField(default=0, verbose_name='sessions总量'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='total_unsubscribe',
            field=models.IntegerField(default=0, verbose_name='Unsubscribe总量'),
        ),
    ]
