# Generated by Django 2.1 on 2019-08-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0123_auto_20190803_1008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboard',
            options={},
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='avg_click_rate',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Click Rate'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='avg_conversion_rate',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Conversion Rate'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='avg_open_rate',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Open Rate'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='avg_repeat_purchase_rate',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Repeat Purchase Rate'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='avg_unsubscribe_rate',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Unsubscribe Rate'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='orders',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Orders'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='revenue',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Revenue'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='session',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='session'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='total_click',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Click总量'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='total_open',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Open总量'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='total_orders',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Orders'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='total_revenue',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Revenue'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='total_sent',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Sent总量'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='total_sessions',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='sessions总量'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='total_unsubscribe',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Unsubscribe总量'),
        ),
    ]
