# Generated by Django 2.1 on 2019-08-03 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0124_auto_20190803_1108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customergroup',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='dashboard',
            options={'managed': False},
        ),
    ]
