# Generated by Django 2.1 on 2019-08-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0125_auto_20190803_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customergroup',
            name='uuid',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='收件人列表ID'),
        ),
    ]
