# Generated by Django 2.1 on 2019-08-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0126_auto_20190803_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customergroup',
            name='customer_list',
            field=models.TextField(blank=True, null=True, verbose_name='对应客户列表'),
        ),
        migrations.AlterField(
            model_name='customergroup',
            name='relation_info',
            field=models.TextField(blank=True, null=True, verbose_name='客户关系'),
        )
    ]
