# Generated by Django 2.1 on 2019-08-03 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0127_auto_20190803_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkoutevent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customergroup',
            options={'managed': False},
        ),
    ]
