# Generated by Django 2.1 on 2019-08-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0128_auto_20190803_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutevent',
            name='cart_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='cart_token'),
        ),
    ]
