# Generated by Django 2.1 on 2019-08-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0129_checkoutevent_cart_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutevent',
            name='cart_token',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='cart_token'),
        ),
    ]
